services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      pull: true
    container_name: app
    restart: unless-stopped
    stdin_open: true
    volumes:
      - ./data/host-configs:/data/host-configs
      - ./data/mod-configs:/data/mod-configs
      - ./data/saves:/data
      - ./data/mods:/data/Mods
      - ./data/logs:/data/Logs
    ports:
      - "42420:42420/tcp"
